server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/saelu/microservces-spring-cloud-config-store
          search-paths:
            - 'service-config/*service'
#          username: root
#          password: 232232
